version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongoedu
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=dev
      - MONGO_INITDB_ROOT_PASSWORD=1234dev
      - MONGO_INITDB_DATABASE=educacioncontinua

  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "3000:3000"
    depends_on:
      - mongo

volumes:
  mongo-data:
    driver: local
